apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: sensordb
    user: sensor
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
      timescaledb: true
    secureJsonData:
      password: 'sensor'
    isDefault: true
    editable: true